package com.servicerca.service; import com.servicerca.dto.auth.*;import com.servicerca.exception.BusinessException;import com.servicerca.mapper.ApiMapper;import com.servicerca.model.*;import com.servicerca.repository.*;import com.servicerca.security.*;import lombok.extern.slf4j.Slf4j;import org.springframework.beans.factory.annotation.Value;import org.springframework.security.authentication.*;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;
@Service @Slf4j public class AuthService{private final AuthenticationManager authentication;private final UserRepository users;private final RefreshTokenRepository refreshes;private final RecoveryTokenRepository recoveries;private final PasswordEncoder encoder;private final JwtService jwt;private final ApiMapper mapper;@Value("${app.frontend-url}")String frontend;@Value("${app.recovery-log-enabled:false}")boolean logRecovery;public AuthService(AuthenticationManager a,UserRepository u,RefreshTokenRepository f,RecoveryTokenRepository r,PasswordEncoder e,JwtService j,ApiMapper m){authentication=a;users=u;refreshes=f;recoveries=r;encoder=e;jwt=j;mapper=m;}
 public AuthResponse login(LoginRequest r){var a=authentication.authenticate(new UsernamePasswordAuthenticationToken(r.email(),r.password()));return issue(((SecurityUser)a.getPrincipal()).user());}
 @Transactional public AuthResponse register(RegisterRequest r){if(!r.acceptedPolicies())throw new BusinessException("POLICIES_REQUIRED","Debés aceptar las políticas.");if(users.findByEmailIgnoreCaseAndDeletedAtIsNull(r.email()).isPresent())throw new BusinessException("EMAIL_EXISTS","El email ya está registrado.");var u=User.builder().email(r.email().trim().toLowerCase()).passwordHash(encoder.encode(r.password())).build();users.save(u);return issue(u);}
 @Transactional public AuthResponse refresh(RefreshTokenRequest r){var t=refreshes.findByTokenHashAndRevokedAtIsNull(hash(r.refreshToken())).filter(x->x.getExpiresAt().isAfter(Instant.now())).orElseThrow(()->new BusinessException("INVALID_REFRESH_TOKEN","La sesión venció."));t.setRevokedAt(Instant.now());return issue(t.getUser());}
 @Transactional public void forgot(RecoveryRequest r){users.findByEmailIgnoreCaseAndDeletedAtIsNull(r.email()).ifPresent(u->{var raw=random();recoveries.save(RecoveryToken.builder().user(u).tokenHash(hash(raw)).expiresAt(Instant.now().plusSeconds(1800)).build());if(logRecovery)log.info("DEV password recovery endpoint: {}/reset-password?token={}",frontend,raw);});}
 @Transactional public void reset(ResetPasswordRequest r){var t=recoveries.findByTokenHashAndUsedAtIsNullAndExpiresAtAfter(hash(r.token()),Instant.now()).orElseThrow(()->new BusinessException("INVALID_RECOVERY_TOKEN","El enlace es inválido o venció."));t.getUser().setPasswordHash(encoder.encode(r.password()));t.setUsedAt(Instant.now());}
 private AuthResponse issue(User u){var raw=random();refreshes.save(RefreshToken.builder().user(u).tokenHash(hash(raw)).expiresAt(Instant.now().plus(Duration.ofDays(30))).build());return new AuthResponse("Bearer",jwt.generateToken(u),raw,jwt.getExpirationSeconds(),mapper.toUserResponse(u));}
 private static String random(){return Base64.getUrlEncoder().withoutPadding().encodeToString((UUID.randomUUID()+""+UUID.randomUUID()).getBytes());}private static String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
