package com.servicerca.service; import com.servicerca.dto.notification.NotificationEventResponse;import com.servicerca.dto.request.*;import com.servicerca.exception.*;import com.servicerca.mapper.ApiMapper;import com.servicerca.model.*;import com.servicerca.repository.*;import org.springframework.messaging.simp.SimpMessagingTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service public class ServiceRequestService{private final ServiceRequestRepository requests;private final ServiceApplicationRepository applications;private final TradeRepository trades;private final UserRepository users;private final ReportRepository reports;private final ApiMapper mapper;private final SimpMessagingTemplate events;public ServiceRequestService(ServiceRequestRepository r,ServiceApplicationRepository a,TradeRepository t,UserRepository u,ReportRepository x,ApiMapper m,SimpMessagingTemplate e){requests=r;applications=a;trades=t;users=u;reports=x;mapper=m;events=e;}
 @Transactional(readOnly=true)public List<ServiceRequestResponse> mine(User u){return requests.findByClientIdAndDeletedAtIsNullOrderByCreatedAtDesc(u.getId()).stream().map(r->view(r,u)).toList();}
 @Transactional(readOnly=true)public List<ServiceRequestResponse> feed(User p){var u=users.findById(p.getId()).orElseThrow();if(!u.isProfessionalEnabled()||!u.isAvailable()||u.getLocality()==null)return List.of();return requests.findFeed(u.getId(),u.getLocality(),u.getTrades(),Set.of(RequestStatus.PUBLISHED,RequestStatus.HAS_APPLICANTS)).stream().filter(r->applications.findByRequestIdAndProfessionalId(r.getId(),u.getId()).isEmpty()).filter(r->!reports.existsByReporterIdAndReportedUserId(u.getId(),r.getClient().getId())).map(r->view(r,u)).toList();}
 @Transactional public ServiceRequestResponse create(User p,CreateServiceRequest body){var r=ServiceRequest.builder().client(users.findById(p.getId()).orElseThrow()).trade(trades.findById(body.tradeId()).orElseThrow(()->new ResourceNotFoundException("Oficio inexistente."))).title(body.title()).description(body.description()).locality(body.locality().trim()).latitude(body.latitude()).longitude(body.longitude()).urgency(body.urgency()).budget(body.budget()).status(RequestStatus.PUBLISHED).build();requests.save(r);notifyLocality(r,"REQUEST_CREATED","Hay un nuevo pedido de "+r.getTrade().getName());return view(r,p);}
 @Transactional public ServiceRequestResponse apply(User p,UUID id,ApplyToServiceRequest body){var u=users.findById(p.getId()).orElseThrow();var r=requests.findLocked(id).orElseThrow(()->new ResourceNotFoundException("Pedido inexistente."));if(!Set.of(RequestStatus.PUBLISHED,RequestStatus.HAS_APPLICANTS).contains(r.getStatus())||!u.isProfessionalEnabled()||!u.getTrades().contains(r.getTrade())||!u.getLocality().equalsIgnoreCase(r.getLocality()))throw new BusinessException("REQUEST_UNAVAILABLE","El pedido ya no está disponible.");var a=applications.findByRequestIdAndProfessionalId(id,u.getId()).orElseGet(()->ServiceApplication.builder().request(r).professional(u).build());a.setMessage(body.message());a.setStatus(ApplicationStatus.PENDING);applications.save(a);r.setStatus(RequestStatus.HAS_APPLICANTS);notifyUser(r.getClient(),r,"NEW_APPLICATION","Recibiste una nueva postulación.");return view(r,u);}
 @Transactional public void dismiss(User p,UUID id){var r=requests.findById(id).orElseThrow(()->new ResourceNotFoundException("Pedido inexistente."));var a=applications.findByRequestIdAndProfessionalId(id,p.getId()).orElseGet(()->ServiceApplication.builder().request(r).professional(users.findById(p.getId()).orElseThrow()).build());a.setStatus(ApplicationStatus.DECLINED);applications.save(a);}
 @Transactional public ServiceRequestResponse select(User p,UUID requestId,UUID applicationId){var r=requests.findLocked(requestId).orElseThrow(()->new ResourceNotFoundException("Pedido inexistente."));if(!r.getClient().getId().equals(p.getId()))throw new BusinessException("FORBIDDEN","Solo el cliente puede elegir.");if(r.getSelectedApplication()!=null)throw new BusinessException("ALREADY_ASSIGNED","Ya elegiste un profesional.");var selected=applications.findById(applicationId).filter(a->a.getRequest().getId().equals(requestId)&&a.getStatus()==ApplicationStatus.PENDING).orElseThrow(()->new ResourceNotFoundException("Postulación inexistente."));r.setSelectedApplication(selected);r.setStatus(RequestStatus.ASSIGNED);applications.findByRequestIdOrderByCreatedAt(requestId).forEach(a->a.setStatus(a.getId().equals(applicationId)?ApplicationStatus.SELECTED:ApplicationStatus.REJECTED));notifyUser(selected.getProfessional(),r,"MATCH","¡El cliente te eligió!");return view(r,p);}
 @Transactional public ServiceRequestResponse start(User p,UUID id){var r=matched(p,id);r.setStatus(RequestStatus.IN_PROGRESS);return view(r,p);}
 @Transactional public ServiceRequestResponse complete(User p,UUID id){var r=matched(p,id);if(r.getClient().getId().equals(p.getId()))r.setClientCompleted(true);else r.setProfessionalCompleted(true);r.setStatus(r.isClientCompleted()&&r.isProfessionalCompleted()?RequestStatus.COMPLETED:RequestStatus.PENDING_CONFIRMATION);return view(r,p);}
 private ServiceRequest matched(User p,UUID id){var r=requests.findLocked(id).orElseThrow(()->new ResourceNotFoundException("Pedido inexistente."));if(r.getSelectedApplication()==null||(!r.getClient().getId().equals(p.getId())&&!r.getSelectedApplication().getProfessional().getId().equals(p.getId())))throw new BusinessException("FORBIDDEN","No participás de este trabajo.");return r;}
 private ServiceRequestResponse view(ServiceRequest r,User u){return mapper.toServiceRequestResponse(r,applications.findByRequestIdOrderByCreatedAt(r.getId()),u);}private void notifyUser(User u,ServiceRequest r,String type,String msg){events.convertAndSend("/topic/user/"+u.getId(),new NotificationEventResponse(type,r.getId(),msg,Instant.now()));}private void notifyLocality(ServiceRequest r,String type,String msg){events.convertAndSend("/topic/locality/"+r.getLocality().toLowerCase().replaceAll("[^a-z0-9]","-"),new NotificationEventResponse(type,r.getId(),msg,Instant.now()));}
}
