package com.servicerca.security;
import com.servicerca.repository.UserRepository;import org.springframework.beans.factory.annotation.Value;import org.springframework.context.annotation.*;import org.springframework.security.authentication.*;import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;import org.springframework.security.config.annotation.web.builders.HttpSecurity;import org.springframework.security.config.http.SessionCreationPolicy;import org.springframework.security.core.userdetails.*;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.security.web.SecurityFilterChain;import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;import org.springframework.web.cors.*;import java.util.List;
@Configuration public class SecurityConfig{
 private final JwtAuthenticationFilter filter;private final OAuthSuccessHandler oauth;
 public SecurityConfig(JwtAuthenticationFilter f,OAuthSuccessHandler o){filter=f;oauth=o;}
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder(12);}
 @Bean UserDetailsService userDetailsService(UserRepository users){return email->new SecurityUser(users.findByEmailIgnoreCaseAndDeletedAtIsNull(email).orElseThrow(()->new UsernameNotFoundException(email)));}
 @Bean AuthenticationManager authenticationManager(AuthenticationConfiguration c)throws Exception{return c.getAuthenticationManager();}
 @Bean SecurityFilterChain chain(HttpSecurity h)throws Exception{return h.csrf(c->c.disable()).cors(c->{}).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/v1/auth/**","/oauth2/**","/login/**","/actuator/health","/swagger-ui/**","/swagger-ui.html","/v3/api-docs/**","/ws/**").permitAll().anyRequest().authenticated()).oauth2Login(o->o.successHandler(oauth)).addFilterBefore(filter,UsernamePasswordAuthenticationFilter.class).build();}
 @Bean CorsConfigurationSource cors(@Value("${app.frontend-url}")String origin){var c=new CorsConfiguration();c.setAllowedOrigins(List.of(origin));c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("*"));c.setAllowCredentials(true);var s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
}
